version: "3.4"

services:
  web:
    image: gitea/gitea:1.12.4
    volumes:
      - ./data:/data
    ports:
      - "2223:22"
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?MYSQL_ROOT_PASSWORD not set}
      - MYSQL_DATABASE=${MYSQL_DATABASE?MYSQL_DATABASE not set}
      - MYSQL_USER=${MYSQL_USER?MYSQL_USER not set}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?MYSQL_PASSWORD not set}
    volumes:
      - ./db/:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - ${PORT?PORT not set}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
